import React from "react";
import "./SolarProducts.css";

const SolarProducts = () => {
  return (
    <div className="container-main solar-products">
      <div className="wrapper">
        <div className="inner-wrapper">
          <h1 className="page-header">Solar Products</h1>
          <div className="content">
            <h2>Products</h2>
            <p>
              Solar installation requires a range of products and components to
              effectively harness solar energy and convert it into usable
              electricity. Here’s a list of essential products required for
              solar panel installation:
            </p>
            <div class="cards-container">
              <div class="card">
                <img src="solar-panels.jpg" alt="Solar Panels" />
                <h3>Solar Panels</h3>
                <p>
                Photovoltaic (PV) panels are the primary component of any solar energy system. These panels contain solar cells that capture sunlight and convert it into electricity.
                </p>
              </div>
              <div class="card">
                <img src="mounting-hardware.jpg" alt="Mounting Hardware" />
                <h3>Mounting Hardware</h3>
                <p>
                Mounting hardware is used to securely attach solar panels to various surfaces, such as rooftops or ground-mounted structures. This includes rails, clamps, brackets, and racking systems.
                </p>
              </div>
              <div class="card">
                <img src="inverters.jpg" alt="Inverters" />
                <h3>Inverters</h3>
                <p>
                Inverters are essential for converting the direct current (DC) electricity generated by solar panels into alternating current (AC) electricity that can be used to power electrical devices and appliances in homes or businesses
                </p>
              </div>
              <div class="card">
                <img
                  src="racking-mounting.jpg"
                  alt="Racking & Mounting Systems"
                />
                <h3>Racking & Mounting Systems</h3>
                <p>
                Racking and mounting systems provide the structural support needed to secure solar panels in place. These systems are designed to withstand various weather conditions and ensure proper alignment and orientation for optimal sunlight exposure.
                </p>
              </div>
              <div class="card">
                <img src="solar-batteries.jpg" alt="Solar Batteries" />
                <h3>Solar Batteries</h3>
                <p>
                Solar batteries store excess electricity generated by solar panels for use during times when sunlight is unavailable, such as at night or during cloudy weather. Batteries can enhance energy independence and resilience by providing backup power during grid outage.
                </p>
              </div>
              <div class="card">
                <img
                  src="electrical-wiring.jpg"
                  alt="Electrical Wiring & Connectors"
                />
                <h3>Electrical Wiring & Connectors</h3>
                <p>
                Electrical wiring and connectors are used to connect solar panels, inverters, batteries, and other components of the solar energy system. Proper wiring and connections are crucial for ensuring safe and efficient operation.
                </p>
              </div>
              <div class="card">
                <img
                  src="electrical-wiring.jpg"
                  alt="Charge Controllers"
                />
                <h3>Charge Controllers</h3>
                <p>
                Charge controllers regulate the flow of electricity from solar panels to batteries in off-grid solar systems. They prevent overcharging and ensure the longevity of the battery bank.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SolarProducts;
